[package]
name = "defibank"
version = "1.0.0"
authors = []

[addresses]
SmarTech = "0xeee5bd9d935c8c2d6fe960acd0a30976945f72ff753397c2f2be7e33fc596c2d"

[dev-addresses]

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
